version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "student-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3ppr4pu597bl"
s3_prefix = "student-api-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
